# Country code conversion utility
# Converts country names to 2-letter ISO codes

#### GET COUNTRY CODE HELPER ####


def get_country_code(country_name):
    
    """Convert country name/code to 2-letter ISO country code"""

    country_codes = {
        "ANDORRA": "AD",
        "UNITED ARAB EMIRATES": "AE",
        "AFGHANISTAN": "AF",
        "ANTIGUA AND BARBUDA": "AG",
        "ANGUILLA": "AI",
        "ALBANIA": "AL",
        "ARMENIA": "AM",
        "ANGOLA": "AO",
        "ANTARCTICA": "AQ",
        "ARGENTINA": "AR",
        "AMERICAN SAMOA": "AS",
        "AUSTRIA": "AT",
        "AUSTRALIA": "AU",
        "ARUBA": "AW",
        "ALAND ISLANDS": "AX",
        "AZERBAIJAN": "AZ",
        "BOSNIA AND HERZEGOVINA": "BA",
        "BARBADOS": "BB",
        "BANGLADESH": "BD",
        "BELGIUM": "BE",
        "BURKINA FASO": "BF",
        "BULGARIA": "BG",
        "BAHRAIN": "BH",
        "BURUNDI": "BI",
        "BENIN": "BJ",
        "SAINT BARTHELEMY": "BL",
        "BERMUDA": "BM",
        "BRUNEI DARUSSALAM": "BN",
        "BRUNEI": "BN",
        "BOLIVIA": "BO",
        "BONAIRE, SINT EUSTATIUS AND SABA": "BQ",
        "BRAZIL": "BR",
        "BAHAMAS": "BS",
        "BHUTAN": "BT",
        "BOUVET ISLANDS": "BV",
        "BOTSWANA": "BW",
        "BELARUS": "BY",
        "BELIZE": "BZ",
        "CANADA": "CA",
        "COCOS (KEELING) ISLANDS": "CC",
        "DEMOCRATIC REPUBLIC OF THE CONGO": "CD",
        "CENTRAL AFRICAN REPUBLIC": "CF",
        "CONGO": "CG",
        "SWITZERLAND": "CH",
        "COTE D'IVOIRE": "CI",
        "IVORY COAST": "CI",
        "COOK ISLANDS": "CK",
        "CHILE": "CL",
        "CAMEROON": "CM",
        "CHINA": "CN",
        "COLOMBIA": "CO",
        "COSTA RICA": "CR",
        "CUBA": "CU",
        "CAPE VERDE": "CV",
        "CURACAO": "CW",
        "CHRISTMAS ISLAND": "CX",
        "CYPRUS": "CY",
        "CZECH REPUBLIC": "CZ",
        "GERMANY": "DE",
        "DJIBOUTI": "DJ",
        "DENMARK": "DK",
        "DOMINICA": "DM",
        "DOMINICAN REPUBLIC": "DO",
        "ALGERIA": "DZ",
        "ECUADOR": "EC",
        "ESTONIA": "EE",
        "EGYPT": "EG",
        "WEST SAHARA": "EH",
        "ERITREA": "ER",
        "SPAIN": "ES",
        "ETHIOPIA": "ET",
        "FINLAND": "FI",
        "FIJI": "FJ",
        "FALKLAND ISLANDS": "FK",
        "MICRONESIA": "FM",
        "FAROE ISLANDS": "FO",
        "FRANCE": "FR",
        "GABON": "GA",
        "UNITED KINGDOM": "GB",
        "UK": "GB",
        "GREAT BRITAIN": "GB",
        "GRENADA": "GD",
        "GEORGIA": "GE",
        "FRENCH GUYANA": "GF",
        "GUERNSEY": "GG",
        "GHANA": "GH",
        "GIBRALTAR": "GI",
        "GREENLAND": "GL",
        "GAMBIA": "GM",
        "GUINEA": "GN",
        "GUADELOUPE": "GP",
        "EQUATORIAL GUINEA": "GQ",
        "GREECE": "GR",
        "SOUTH GEORGIA AND THE SOUTHERN SANDWICH ISLANDS": "GS",
        "GUATEMALA": "GT",
        "GUAM": "GU",
        "GUINEA-BISSAU": "GW",
        "GUYANA": "GY",
        "HONG KONG": "HK",
        "HEARD AND MCDONALD ISLANDS": "HM",
        "HONDURAS": "HN",
        "CROATIA": "HR",
        "HAITI": "HT",
        "HUNGARY": "HU",
        "INDONESIA": "ID",
        "IRELAND": "IE",
        "ISRAEL": "IL",
        "ISLE OF MAN": "IM",
        "INDIA": "IN",
        "BRITISH INDIAN OCEAN TERRITORY": "IO",
        "IRAQ": "IQ",
        "IRAN": "IR",
        "ICELAND": "IS",
        "ITALY": "IT",
        "JERSEY": "JE",
        "JAMAICA": "JM",
        "JORDAN": "JO",
        "JAPAN": "JP",
        "KENYA": "KE",
        "KYRGYZSTAN": "KG",
        "CAMBODIA": "KH",
        "KIRIBATI": "KI",
        "COMOROS": "KM",
        "SAINT KITTS AND NEVIS": "KN",
        "NORTH KOREA": "KP",
        "SOUTH KOREA": "KR",
        "KOREA": "KR",
        "KUWAIT": "KW",
        "CAYMAN ISLANDS": "KY",
        "KAZAKHSTAN": "KZ",
        "LAOS": "LA",
        "LEBANON": "LB",
        "ST. LUCIA": "LC",
        "SAINT LUCIA": "LC",
        "LIECHTENSTEIN": "LI",
        "SRI LANKA": "LK",
        "LIBERIA": "LR",
        "LESOTHO": "LS",
        "LITHUANIA": "LT",
        "LUXEMBOURG": "LU",
        "LATVIA": "LV",
        "LIBYA": "LY",
        "MOROCCO": "MA",
        "MONACO": "MC",
        "MOLDOVA": "MD",
        "MONTENEGRO": "ME",
        "SAINT MARTIN": "MF",
        "MADAGASCAR": "MG",
        "MARSHALL ISLANDS": "MH",
        "NORTH MACEDONIA": "MK",
        "MACEDONIA": "MK",
        "MALI": "ML",
        "MYANMAR": "MM",
        "MONGOLIA": "MN",
        "MACAO": "MO",
        "NORTH MARIANA ISLANDS": "MP",
        "MARTINIQUE": "MQ",
        "MAURITANIA": "MR",
        "MONTSERRAT": "MS",
        "MALTA": "MT",
        "MAURITIUS": "MU",
        "MALDIVES": "MV",
        "MALAWI": "MW",
        "MEXICO": "MX",
        "MALAYSIA": "MY",
        "MOZAMBIQUE": "MZ",
        "NAMIBIA": "NA",
        "NEW CALEDONIA": "NC",
        "NIGER": "NE",
        "NORFOLK ISLANDS": "NF",
        "NIGERIA": "NG",
        "NICARAGUA": "NI",
        "NETHERLANDS": "NL",
        "NORWAY": "NO",
        "NEPAL": "NP",
        "NAURU": "NR",
        "NIUE": "NU",
        "NEW ZEALAND": "NZ",
        "OMAN": "OM",
        "PANAMA": "PA",
        "PERU": "PE",
        "FRENCH POLYNESIA": "PF",
        "PAPUA NEW GUINEA": "PG",
        "PHILIPPINES": "PH",
        "PAKISTAN": "PK",
        "POLAND": "PL",
        "ST. PIERRE AND MIQUELON": "PM",
        "PITCAIRN ISLANDS": "PN",
        "PUERTO RICO": "PR",
        "PALESTINE, STATE OF": "PS",
        "PALESTINE": "PS",
        "PORTUGAL": "PT",
        "PALAU": "PW",
        "PARAGUAY": "PY",
        "QATAR": "QA",
        "REUNION": "RE",
        "ROMANIA": "RO",
        "SERBIA": "RS",
        "RUSSIAN FEDERATION": "RU",
        "RUSSIA": "RU",
        "SAINT RW": "RW",
        "RWANDA": "RW",
        "SAUDI ARABIA": "SA",
        "SOLOMON ISLANDS": "SB",
        "SEYCHELLES": "SC",
        "SUDAN": "SD",
        "SWEDEN": "SE",
        "SINGAPORE": "SG",
        "ST. HELENA": "SH",
        "SAINT HELENA": "SH",
        "SLOVENIA": "SI",
        "SVALBARD": "SJ",
        "SLOVAKIA": "SK",
        "SIERRA LEONE": "SL",
        "SAN MARINO": "SM",
        "SENEGAL": "SN",
        "SOMALIA": "SO",
        "SURINAME": "SR",
        "REPUBLIC OF SOUTH SUDAN": "SS",
        "SOUTH SUDAN": "SS",
        "SAO TOME AND PRINCIPE": "ST",
        "EL SALVADOR": "SV",
        "SINT MAARTEN": "SX",
        "SYRIA": "SY",
        "THE KINGDOM OF ESWATINI": "SZ",
        "ESWATINI": "SZ",
        "SWAZILAND": "SZ",
        "TURKSH CAICOSIN": "TC",
        "TURKS AND CAICOS": "TC",
        "CHAD": "TD",
        "FRENCH SOUTHERN TERRITORIES": "TF",
        "TOGO": "TG",
        "THAILAND": "TH",
        "TAJIKISTAN": "TJ",
        "TOKELAU ISLANDS": "TK",
        "TIMOR-LESTE": "TL",
        "TURKMENISTAN": "TM",
        "TUNISIA": "TN",
        "TONGA": "TO",
        "THE REPUBLIC OF TURKIYE": "TR",
        "TURKEY": "TR",
        "TURKIYE": "TR",
        "TRINIDAD AND TOBAGO": "TT",
        "TUVALU": "TV",
        "TAIWAN": "TW",
        "TANZANIA": "TZ",
        "UKRAINE": "UA",
        "UGANDA": "UG",
        "AMERICAN MINOR OUTLYING ISLANDS": "UM",
        "UNITED STATES": "US",
        "USA": "US",
        "US": "US",
        "URUGUAY": "UY",
        "UZBEKISTAN": "UZ",
        "VATICAN CITY": "VA",
        "ST. VINCENT": "VC",
        "SAINT VINCENT": "VC",
        "VENEZUELA": "VE",
        "BRITISH VIRGIN ISLANDS": "VG",
        "AMERICAN VIRGIN ISLANDS": "VI",
        "VIETNAM": "VN",
        "VANUATU": "VU",
        "WALLIS AND FUTUNA ISLANDS": "WF",
        "SAMOA": "WS",
        "YEMEN": "YE",
        "MAYOTTE": "YT",
        "SOUTH AFRICA": "ZA",
        "ZAMBIA": "ZM",
        "ZIMBABWE": "ZW",
    }

    if not country_name:

        return "US"  # Default to US

    # Clean and normalize the input

    country_upper = country_name.strip().upper()

    # Try exact match first

    if country_upper in country_codes:

        return country_codes[country_upper]

    # If already a 2-letter code, return as-is

    if len(country_upper) == 2 and country_upper.isalpha():

        return country_upper

    # Default to US if not found

    return "US"